[package]
name = "num_guess"
version = "0.1.0"
authors = ["ight <thelight.prakash247@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

# add rand crate for random numbers
rand = "0.3.14"
